/**
 * Icon subset generator.
 *
 * Scans the source for every icon name actually used, resolves each to its
 * Material Symbols codepoint, and emits two artefacts:
 *
 *   lib/icon-codepoints.ts   name -> codepoint map, consumed by <Icon>
 *   /tmp/ms-subset.woff2     the font cut down to only those glyphs
 *
 * Rendering by codepoint rather than by ligature name is deliberate: if the
 * font's `liga` feature fails to apply, a ligature-based icon renders its raw
 * icon name as text — a failure that must not happen during a live
 * presentation. Subsetting keeps the embedded font at ~70KB rather than 3.8MB.
 *
 * The name -> codepoint table is read out of the font's own cmap, so it can
 * never drift from the font that is actually shipped.
 *
 * Run this after adding an icon anywhere, then rebuild.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import path from "node:path";

const APP = "/home/claude/ent-mdt";
const FONT = path.join(APP, "node_modules/material-symbols/material-symbols-outlined.woff2");

/* ---- 1. Every icon name referenced in the source ---- */

const SKIP = new Set(["node_modules", ".next", "out", ".git"]);
const files = [];
(function walk(dir) {
  for (const e of readdirSync(dir)) {
    if (SKIP.has(e)) continue;
    const p = path.join(dir, e);
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx|ts)$/.test(p) && !p.endsWith("icon-codepoints.ts")) files.push(p);
  }
})(APP);

/**
 * Icon names are not always literals at the call site — several are looked up
 * through maps (DISCIPLINE_ICON, TIMELINE_ICON, …) or chosen by a ternary. So
 * rather than parse call sites, collect every snake_case-ish string literal in
 * the source and intersect it with the font's glyph names. The intersection is
 * exact, and a few extra candidates cost nothing.
 */
const candidates = new Set();
for (const f of files) {
  const src = readFileSync(f, "utf8");
  for (const m of src.matchAll(/["'`]([a-z][a-z0-9_]{1,40})["'`]/g)) candidates.add(m[1]);
}

/* ---- 2. Resolve against the font's own cmap ---- */

const cmapJson = execFileSync(
  "python3",
  [
    "-c",
    `import json,sys
from fontTools.ttLib import TTFont
f = TTFont(sys.argv[1])
rev = {}
for cp, g in f.getBestCmap().items():
    rev.setdefault(g, cp)
json.dump(rev, sys.stdout)`,
    FONT,
  ],
  { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
);
const glyphs = JSON.parse(cmapJson);

const resolved = new Map();
for (const n of [...candidates].sort()) {
  if (Object.prototype.hasOwnProperty.call(glyphs, n)) resolved.set(n, glyphs[n]);
}

if (resolved.size === 0) throw new Error("No icons resolved — the font layout changed.");

/* ---- 3. Emit the map ---- */

const entries = [...resolved.entries()]
  .map(([n, cp]) => `  ${JSON.stringify(n)}: "\\u{${cp.toString(16)}}",`)
  .join("\n");

writeFileSync(
  path.join(APP, "lib/icon-codepoints.ts"),
  `/**
 * Icon name to Material Symbols codepoint.
 *
 * The Icon component renders the codepoint rather than the ligature name.
 * That removes the dependency on the font's \`liga\` feature — when it fails,
 * the raw icon name is displayed as text — and lets the font be subset down to
 * only the icons actually in use.
 *
 * Generated by single/icons.mjs from the font's own cmap. Do not edit by hand.
 */

export const ICON_CODEPOINTS: Record<string, string> = {
${entries}
};
`,
);

/* ---- 4. Subset the font to exactly those glyphs ---- */

const unicodes = [...resolved.values()].map((cp) => "U+" + cp.toString(16)).join(",");

execFileSync(
  "pyftsubset",
  [
    FONT,
    "--flavor=woff2",
    "--output-file=/tmp/ms-subset.woff2",
    `--unicodes=${unicodes}`,
    "--layout-features=",
    "--no-hinting",
    "--desubroutinize",
  ],
  { stdio: "inherit" },
);

console.log(`Icons: ${resolved.size} glyphs subset from ${candidates.size} candidate strings.`);
